-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."board_invitations" add column "email_device_type" text
--  null;
